<?php

namespace App\Services\Accurate;

class EndpointFieldProvider
{
    private array $endpointFields = [
        'api/item/list.do' => [
            'allQuantity', 'allQuantityUnit2', 'allQuantityUnit3', 'allQuantityUnit4', 'allQuantityUnit5',
            'availableToSell', 'availableToSellInAllUnit', 'availableToSellUnit2', 'availableToSellUnit3',
            'availableToSellUnit4', 'availableToSellUnit5', 'balanceTotalCost', 'balanceUnitCost', 'branch',
            'branchPrice', 'branchPrice2', 'branchPrice3', 'branchPrice4', 'branchPrice5',
            'calculateGroupPrice', 'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9', 'codeItemTax', 'createDate',
            'dateField1', 'dateField2', 'defaultDiscount', 'detailGroup', 'detailGroupModifier',
            'detailItemImage', 'id', 'itemBranchName', 'itemBrand', 'itemCategory', 'itemType',
            'itemTypeName', 'itemUnit', 'lastUpdate', 'manageExpired', 'manageSN', 'minimumQuantityReorder',
            'minimumSellingQuantity', 'name', 'no', 'notes', 'numericField1', 'numericField10',
            'numericField2', 'numericField3', 'numericField4', 'numericField5', 'numericField6',
            'numericField7', 'numericField8', 'numericField9', 'onOrder', 'onOrderPo', 'percentTaxable',
            'preferedVendor', 'printDetailGroup', 'quantity', 'quantityOnReversePurchaseInvoice',
            'ratio2', 'ratio3', 'ratio4', 'ratio5', 'serialNumberType', 'suspended', 'tax1', 'tax2',
            'tax3', 'tax4', 'unit1', 'unit2', 'unit2Price', 'unit3', 'unit3Price', 'unit4', 'unit4Price',
            'unit5', 'unit5Price', 'unitPrice', 'upcNo', 'useWholesalePrice', 'variantDetail1',
            'variantDetail2', 'variantParent', 'vendorPrice', 'vendorUnit',
        ],
        'api/item-category/list.do' => ['id', 'number', 'parent', 'nameWithIndent', 'name'],
        'api/item-adjustment/list.do' => [
            'approvalStatus', 'branch', 'createdByUserName', 'description', 'detailItem',
            'id', 'number', 'totalAmount', 'transDate',
        ],
        'api/item-transfer/list.do' => [
            'approvalStatus', 'branch',
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9',
            'createDate', 'createdByUserName',
            'dateField1', 'dateField2',
            'description',
            'id',
            'itemTransferOutStatusName', 'itemTransferTypeName',
            'lastUpdate',
            'number',
            'numericField1', 'numericField10', 'numericField2', 'numericField3', 'numericField4',
            'numericField5', 'numericField6', 'numericField7', 'numericField8', 'numericField9',
            'printedByUser', 'printedTime',
            'referenceWarehouse',
            'transDate',
            'warehouse',
        ],
        'api/vendor/list.do' => [
            'balance', 'bbmPin', 'billAddress', 'category', 'charField1', 'charField10', 'charField2',
            'charField3', 'charField4', 'charField5', 'charField6', 'charField7', 'charField8',
            'charField9', 'contactInfo', 'currency', 'dateField1', 'dateField2', 'defaultIncTax',
            'defaultInvoiceDesc', 'defaultPurchaseDisc', 'defaultTerm', 'email', 'fax', 'id',
            'lastBalanceView', 'mobilePhone', 'name', 'nitku', 'npwpNo', 'numericField1',
            'numericField10', 'numericField2', 'numericField3', 'numericField4', 'numericField5',
            'numericField6', 'numericField7', 'numericField8', 'numericField9', 'otherContactInfo1',
            'otherContactInfo2', 'otherContactInfo3', 'suspended', 'taxAddress', 'useBillNumber',
            'vendorNo', 'vendorType', 'workPhone', 'wpName',
        ],
        'api/vendor-category/list.do' => ['id', 'name'],
        'api/vendor-claim/list.do' => [
            'approvalStatus', 'branch',
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9',
            'createdByUserName',
            'dateField1', 'dateField2',
            'description',
            'id',
            'number',
            'numericField1', 'numericField10', 'numericField2', 'numericField3', 'numericField4',
            'numericField5', 'numericField6', 'numericField7', 'numericField8', 'numericField9',
            'transDate',
            'vendor',
        ],
        'api/vendor-price/list.do' => [
            'approvalStatus',
            'description',
            'id',
            'number',
            'transDate',
            'vendor',
        ],
        'api/journal-voucher/list.do' => [
            'branch',
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9',
            'dateField1', 'dateField2',
            'description',
            'id',
            'number',
            'numericField1', 'numericField10', 'numericField2', 'numericField3', 'numericField4',
            'numericField5', 'numericField6', 'numericField7', 'numericField8', 'numericField9',
            'totalAmount',
            'transDate',
            'transNumber',
            'transactionTypeName',
        ],
        'api/other-payment/list.do' => [
            'amount',
            'approvalStatus',
            'bank',
            'branch',
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9',
            'chequeDate', 'chequeNo',
            'createdByUserName',
            'dateField1', 'dateField2',
            'description',
            'id',
            'lastAppKey',
            'monthYear',
            'number',
            'numericField1', 'numericField10', 'numericField2', 'numericField3', 'numericField4',
            'numericField5', 'numericField6', 'numericField7', 'numericField8', 'numericField9',
            'otherPaymentDetailListAccountName', 'otherPaymentDetailListName',
            'payee',
            'paymentEmployee',
            'printedByUser', 'printedTime',
            'rate',
            'transDate',
            'voidCheq',
        ],
        'api/other-deposit/list.do' => [
            'amount',
            'approvalStatus',
            'bank',
            'branch',
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9',
            'chequeDate', 'chequeNo',
            'createdByUserName',
            'dateField1', 'dateField2',
            'description',
            'id',
            'number',
            'numericField1', 'numericField10', 'numericField2', 'numericField3', 'numericField4',
            'numericField5', 'numericField6', 'numericField7', 'numericField8', 'numericField9',
            'payee',
            'printedByUser', 'printedTime',
            'rate',
            'transDate',
            'voidCheq',
        ],
        'api/customer/list.do' => [
            'balance', 'balanceBase', 'balanceList', 'bbmPin', 'billAddress', 'blissUserId', 'branch',
            'category', 'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9', 'checked',
            'consignmentStore', 'contactInfo', 'createDate', 'currency', 'customerBranchName',
            'customerLimitAge', 'customerLimitAgeValue', 'customerLimitAmount', 'customerLimitAmountValue',
            'customerNo', 'customerNoVa', 'dateField1', 'dateField2', 'defaultIncTax', 'defaultInvoiceDesc',
            'defaultProject', 'defaultSalesDisc', 'defaultSalesman', 'defaultTerm', 'defaultWarehouse',
            'discountCategory', 'email', 'fax', 'id', 'idCard', 'lastBalanceView', 'lastUpdate',
            'lookupSubText', 'mobilePhone', 'name', 'nitku', 'npwpNo', 'numericField1', 'numericField10',
            'numericField2', 'numericField3', 'numericField4', 'numericField5', 'numericField6',
            'numericField7', 'numericField8', 'numericField9', 'otherContactInfo1', 'otherContactInfo2',
            'otherContactInfo3', 'owingLimitDescription', 'paymentTerm', 'pkpNo', 'priceCategory',
            'reseller', 'salesman2', 'salesman3', 'salesman4', 'salesman5', 'salesmanNameList',
            'shipAddress', 'suspended', 'taxAddress', 'whatsappNo', 'workPhone', 'wpName',
        ],
        'api/customer-category/list.do' => ['nameparent', 'id', 'name', 'parent'],
        'api/price-category/list.do' => ['defaultCategory', 'description', 'id', 'name'],
        'api/customer-claim/list.do' => [
            'approvalStatus', 'branch',
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9',
            'createdByUserName',
            'customer',
            'dateField1', 'dateField2',
            'description',
            'id',
            'number',
            'numericField1', 'numericField10', 'numericField2', 'numericField3', 'numericField4',
            'numericField5', 'numericField6', 'numericField7', 'numericField8', 'numericField9',
            'transDate',
        ],
        'api/employee/list.do' => [
            'bankAccount', 'bankAccountName', 'bankName',
            'branch',
            'calculatePtkp',
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9',
            'dateField1', 'dateField2',
            'email',
            'id',
            'joinDate',
            'mobilePhone',
            'name',
            'nikNo',
            'npwpNo',
            'number',
            'numericField1', 'numericField10', 'numericField2', 'numericField3', 'numericField4',
            'numericField5', 'numericField6', 'numericField7', 'numericField8', 'numericField9',
            'salesman', 'salesmanUser',
            'suspended',
        ],
        'api/currency/list.do' => ['code', 'id', 'name', 'symbol'],
        'api/bank-transfer/list.do' => [
            'approvalStatus',
            'branch',
            'cashInAmount',
            'cashOutAmount',
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9',
            'createdByUserName',
            'dateField1', 'dateField2',
            'description',
            'fromBank',
            'fromBankAmount',
            'fromBankRate',
            'id',
            'number',
            'numericField1', 'numericField10', 'numericField2', 'numericField3', 'numericField4',
            'numericField5', 'numericField6', 'numericField7', 'numericField8', 'numericField9',
            'purchasePayment',
            'toBank',
            'toBankAmount',
            'toBankRate',
            'toBranch',
            'transDate',
        ],
        'api/expense/list.do' => [
            'amount',
            'approvalStatus',
            'branch',
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4',
            'charField5', 'charField6', 'charField7', 'charField8', 'charField9',
            'createdByUserName',
            'dateField1', 'dateField2',
            'description',
            'dueDate',
            'id',
            'number',
            'numericField1', 'numericField10', 'numericField2', 'numericField3', 'numericField4',
            'numericField5', 'numericField6', 'numericField7', 'numericField8', 'numericField9',
            'paidAmount',
            'transDate',
        ],
        'api/glaccount/list.do' => ['id', 'no', 'asOf', 'memo', 'accountTypeName', 'balance', 'currency', 'accountType', 'name'],
        'api/warehouse/list.do' => [
            'charField1', 'charField10', 'charField2', 'charField3', 'charField4', 'charField5',
            'charField6', 'charField7', 'charField8', 'charField9', 'dateField1', 'dateField2',
            'description', 'id', 'name', 'numericField1', 'numericField10', 'numericField2',
            'numericField3', 'numericField4', 'numericField5', 'numericField6', 'numericField7',
            'numericField8', 'numericField9', 'pic', 'scrapWarehouse', 'suspended',
        ],
    ];

    public function getFieldsForEndpoint(string $endpoint): ?string
    {
        $normalizedEndpoint = ltrim($endpoint, '/');

        if (!isset($this->endpointFields[$normalizedEndpoint])) {
            return null;
        }

        return implode(',', $this->endpointFields[$normalizedEndpoint]);
    }
}
